# Base configs
baseurl: "https://awalkaday.art"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "awalkaday.art Photography Collection"
subtitle: "The sun is out and walking, every day, for you. For a healthier life, let's #awalkaday!"
author: "2021-2024 Chris-Armel (daqhris)"
header:
 title: "awalkaday.art"
 subtitle: "by daqhris"
footer:
 name: "awalkaday.art Photography Collection"
 bio: >
  Let's embark on a journey through a collection of black and white photographs depicting the natural landscapes and architectural wonders of Belgium (Europe) that will inspire you to get out and walk. <br><br>
  Shot by Chris-Armel (daqhris), the photographs pay tribute to the joys of walking in nature and capture fascinating sights discovered, by chance and on foot, in a country of refuge far from tyranny. Feel free to immerse yourself in a self-built digital venue that showcases ageless and time-bound visual memories. <br><br>
  awalkaday.art is an artistic project that has been evolving slowly and publicly since 2017 and then, was suspended in 2018. It was relaunched in 2021, and the creative process of photographing came to an end a year later. The following year, in 2023, a smart contract containing 263 photographs was self-published on the Ethereum blockchain. This year (2024), an immersive virtual hall, which shins a spotlight on 24 photographs, is open for all to visit.    

web_design: "Chris-Armel (daqhris)"
social_urls:
  instagram: "https://www.instagram.com/walk.day"
  github: "https://github.com/awalkaday"
  twitter: "https://twitter.com/awalkadayart"
  
# Links conditions
url: https://awalkaday.art
enforce_ssl: awalkaday.art
