# Base configs
baseurl: "https://daqhris.com/awalkaday/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "WALK≡DAY Visual Arts Gallery"
subtitle: "The sun is up and running, everyday, for you."
author: "Chris-Armel"
header:
 title: "WALK≡DAY"
 subtitle: "by daqhris"
footer:
 name: "WALK≡DAY Visual Arts Gallery"
 bio: "This is a black and white visual arts project that curates images in order to inspire people to get up and go for a walk. #awalkaday"
 github: ""
web_design: "daqhris"
social_urls:
  instagram: "https://www.instagram.com/walk.day"
