# Base configs
baseurl: "https://awalkaday.art"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "awalkaday.art Photography Collection"
subtitle: "The sun is out and walking, every day, for you. For a healthier life, let's #awalkaday!"
author: "2021-2024 Chris-Armel (daqhris)"
header:
 title: "awalkaday.art"
 subtitle: "by daqhris"
footer:
 name: "awalkaday.art Photography Collection"
 bio: "This is a series of black-and-white photographs that highlight the natural landscapes and architectural marvels of Belgium, Europe. 
 Chris-Armel (daqhris) created each piece as a tribute to the joys of walking in nature and capturing the magnificence and mysteries that surround us. 
 Immerse yourself in the photo series of awalkaday.art and embark on a stunning journey of visual exploration!
 Each photograph has a unique identification token on the Ethereum blockchain which certifies its authenticity. 
 A smart contract, named awalkaday.art, was published on the blockchain in February 2023, enabling the purchase of artwork from this collection of photographs."
web_design: "Chris-Armel (daqhris)"
social_urls:
  instagram: "https://www.instagram.com/walk.day"
  github: "https://github.com/awalkaday"
  twitter: "https://twitter.com/awalkadayart"
  
# Links conditions
url: https://awalkaday.art
enforce_ssl: awalkaday.art
