# Base configs
baseurl: "https://awalkaday.art"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "awalkaday.art Photography Collection"
subtitle: "A collection of 263 monochrome photographs shot by Chris-Armel (daqhris) in Belgium (Europe) and published on the Ethereum blockchain"
author: "2017-2024 Chris-Armel (daqhris)"
header:
 title: "awalkaday.art"
 subtitle: "by daqhris"
footer:
 name: "awalkaday.art Photography Collection"
 bio: >
  Let's explore a collection of black-and-white photographs illustrating the charm of natural landscapes and architectural wonders of Belgium (Europe). 
  Shot by Chris-Armel (daqhris), the photographs honor the joy of walking in nature and capture fascinating sights, discovered by chance and on foot, in a country of refuge far from tyranny. Feel free to immerse yourself in a self-built web gallery that showcases ageless and time-bound visual memories. <br><br>
  awalkaday.art is an artistic project that has been slowly and publicly evolving since 2017, and was then suspended in 2018. The project was relaunched in 2021, and the process of photographing came to an end a year later. The following year (2023), a smart contract containing 263 photographs was self-published on the Ethereum blockchain. This year (2024), an immersive virtual hall exhibiting 24 photographs is open to the public.     

web_design: "Chris-Armel (daqhris)"
social_urls:
  instagram: "https://www.instagram.com/walk.day"
  github: "https://github.com/awalkaday"
  twitter: "https://twitter.com/awalkadayart"
  
# Links conditions
url: https://awalkaday.art
enforce_ssl: awalkaday.art
