# Base configs
baseurl: "https://awalkaday.art"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "awalkaday.art Photography Collection"
subtitle: "The sun is up and running, every day, for you. For a healthier life, let's enjoy #awalkaday!"
author: "2021-2023 Chris-Armel (daqhris)"
header:
 title: "awalkaday.art"
 subtitle: "by daqhris"
footer:
 name: "awalkaday.art Photography Collection"
 bio: "A series of black-and-white photographs that highlight the natural landscapes and architectural marvels of Belgium in Europe. 
 Chris-Armel (daqhris) created each piece as a tribute to the joys of walking in nature, capturing the magnificence and mysteries that surround us. 
 Immerse yourself in the photo series and embark on a stunning visual exploration. 
 Each photo in the collection has a unique identification token on the Ethereum blockchain, which certifies its authenticity. 
 A smart contract, named awalkaday.art, was published on the blockchain in February 2023, and enables the purchase of artwork from this photo collection."
web_design: "Chris-Armel (daqhris)"
social_urls:
  instagram: "https://www.instagram.com/walk.day"
  github: "https://github.com/awalkaday"
  twitter: "https://twitter.com/awalkadayart"
  
# Links conditions
url: https://awalkaday.art
enforce_ssl: awalkaday.art
