# Base configs
baseurl: "https://awalkaday.art"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "WALK≡DAY Visual Arts Gallery"
subtitle: "The sun is up and running, everyday, for you. Take #awalkaday for a healthier life."
author: "2017-2021 Chris-Armel"
header:
 title: "WALK≡DAY"
 subtitle: "by daqhris"
footer:
 name: "WALK≡DAY Visual Arts Gallery"
 bio: "WALK≡DAY is a black-and-white visual arts project that curates images in order to inspire people to get up and go for a walk everyday. You may find our photo collections on Instagram where they are shared with #awalkaday."
web_design: "daqhris.com"
social_urls:
  instagram: "https://www.instagram.com/walk.day"
  github: "https://github.com/daqhris/awalkaday"
