# Base configs
baseurl: "https://awalkaday.art"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "awalkaday.art Photography Collection"
subtitle: "A collection of 263 monochrome photographs shot by Chris-Armel (daqhris) in Belgium (Europe) and published on the Ethereum blockchain"
author: "Chris-Armel (daqhris)"
header:
 title: "awalkaday.art"
 subtitle: "by daqhris"
footer:
 name: "awalkaday.art Photography Collection"
 bio: >
  Let's explore a collection of black-and-white photographs illustrating the charm of natural landscapes and architectural wonders of Belgium (Europe). 
  Shot by Chris-Armel (daqhris), the photographs honor the joy of walking in nature and capture fascinating sights, discovered by chance and on foot, in a country of refuge far from tyranny. Feel free to immerse yourself in a self-built web gallery that showcases ageless and time-bound visual memories. <br><br>
  awalkaday.art is a visual art project that has been slowly and publicly evolving since 2017, and was then suspended in 2018. The project was relaunched in 2021, and the process of photographing came to an end a year later. The following year, in 2023, a smart contract containing 263 photographs was minted on the Ethereum blockchain and a small number of the artworks were listed for sale onchain. In the first half of 2024, an immersive virtual exhibition of 24 photographs was opened to the public. In the second half of 2024, an artist's book documenting the photographic odyssey was published online.      

web_design: "Chris-Armel (daqhris)"
social_urls:
  instagram: "https://www.instagram.com/walk.day"
  github: "https://github.com/awalkaday"
  twitter: "https://twitter.com/awalkadayart"
  
# Links conditions
url: https://awalkaday.art
enforce_ssl: awalkaday.art
